spring.application.name=backend-somar

#Database connection
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rozlwwmwldhidchbbemp
spring.datasource.password=UTgc863sZucWH6l9

#